fix(ci): restart snap gateway after connecting interfaces
The release canary for Ubuntu Snap is presently and consistently failing with
an error:

```
Error:   × failed to create /home/runner/.config/openshell/gateways/snap-docker
```

I wasn't able to reproduce this exact error locally, but installing the snap
with the same steps as the release canary job did present a different error
about not being able to connect to the gateway which was fixed by restarting
the gateway after making the snap connections.

Signed-off-by: Kris Hicks <khicks@nvidia.com>